"""removed version column from events table

Revision ID: 7be426bf1a87
Revises: 4d58fa9eb181
Create Date: 2026-01-08 10:12:09.005887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be426bf1a87'
down_revision: Union[str, Sequence[str], None] = '4d58fa9eb181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
